[www]
user = www-data
group = www-data

listen = 0.0.0.0:9000

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; Slow log disabled (no directory)
; slowlog = /var/log/php/slow.log
; request_slowlog_timeout = 5s

; Clear environment
clear_env = no

; Catch worker output
catch_workers_output = yes
