<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Analytics Summary Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            border-bottom: 2px solid #206bc4;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #206bc4;
            margin: 0;
            font-size: 24px;
        }
        
        .header .subtitle {
            color: #666;
            margin: 5px 0;
        }
        
        .meta-info {
            text-align: right;
            font-size: 10px;
            color: #666;
            margin-bottom: 20px;
        }
        
        .section {
            margin-bottom: 30px;
        }
        
        .section-title {
            background-color: #f8f9fa;
            padding: 10px;
            border-left: 4px solid #206bc4;
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 15px;
        }
        
        .kpi-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
            margin-bottom: 20px;
        }
        
        .kpi-bg-white rounded-lg shadow-sm border border-gray-200 {
            flex: 1;
            min-width: 200px;
            border: 1px solid #ddd;
            padding: 15px;
            text-align: center;
            background-color: #f8f9fa;
        }
        
        .kpi-value {
            font-size: 18px;
            font-weight: bold;
            color: #206bc4;
            margin-bottom: 5px;
        }
        
        .kpi-label {
            font-size: 11px;
            color: #666;
            text-transform: uppercase;
        }
        
        .data-min-w-full divide-y divide-gray-200 {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        .data-min-w-full divide-y divide-gray-200 th,
        .data-min-w-full divide-y divide-gray-200 td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        .data-min-w-full divide-y divide-gray-200 th {
            background-color: #f8f9fa;
            font-weight: bold;
            font-size: 11px;
        }
        
        .data-min-w-full divide-y divide-gray-200 td {
            font-size: 10px;
        }
        
        .summary-stats {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        
        .stat-grid grid-cols-12 gap-4 {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        
        .stat-label {
            font-weight: bold;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        @media print {
            body {
                margin: 0;
                padding: 15px;
            }
            
            .kpi-grid {
                display: block;
            }
            
            .kpi-bg-white rounded-lg shadow-sm border border-gray-200 {
                display: inline-block;
                width: 48%;
                margin-bottom: 10px;
            }
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Analytics Summary Report</h1>
        <div class="subtitle">Comprehensive Performance Analytics</div>
    </div>
    
    <!-- Meta Information -->
    <div class="meta-info">
        <div>Generated on: {{ $generated_at->format('F j, Y \a\t g:i A') }}</div>
        <div>Generated by: {{ $generated_by }}</div>
    </div>
    
    <!-- Key Performance Indicators -->
    <div class="section">
        <div class="section-title">Key Performance Indicators</div>
        
        @if(isset($data['kpis']['attendance']))
        <h4>Attendance Metrics</h4>
        <div class="kpi-grid">
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ number_format($data['kpis']['attendance']['rate'], 1) }}%</div>
                <div class="kpi-label">Attendance Rate</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ number_format($data['kpis']['attendance']['punctuality_rate'], 1) }}%</div>
                <div class="kpi-label">Punctuality Rate</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ number_format($data['kpis']['attendance']['absenteeism_rate'], 1) }}%</div>
                <div class="kpi-label">Absenteeism Rate</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ number_format($data['kpis']['attendance']['average_hours_per_day'], 1) }}h</div>
                <div class="kpi-label">Avg Hours/Day</div>
            </div>
        </div>
        @endif
        
        @if(isset($data['kpis']['leave']))
        <h4>Leave Metrics</h4>
        <div class="kpi-grid">
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ $data['kpis']['leave']['total_requests'] }}</div>
                <div class="kpi-label">Total Requests</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ $data['kpis']['leave']['approved'] }}</div>
                <div class="kpi-label">Approved</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ $data['kpis']['leave']['pending'] }}</div>
                <div class="kpi-label">Pending</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ number_format($data['kpis']['leave']['approval_rate'], 1) }}%</div>
                <div class="kpi-label">Approval Rate</div>
            </div>
        </div>
        @endif
        
        @if(isset($data['kpis']['payroll']))
        <h4>Payroll Metrics</h4>
        <div class="kpi-grid">
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">${{ number_format($data['kpis']['payroll']['total_amount'], 0) }}</div>
                <div class="kpi-label">Total Payroll</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">${{ number_format($data['kpis']['payroll']['average_salary'], 0) }}</div>
                <div class="kpi-label">Average Salary</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ number_format($data['kpis']['payroll']['processing_rate'], 1) }}%</div>
                <div class="kpi-label">Processing Rate</div>
            </div>
            <div class="kpi-bg-white rounded-lg shadow-sm border border-gray-200">
                <div class="kpi-value">{{ $data['kpis']['payroll']['total_processed'] }}</div>
                <div class="kpi-label">Processed</div>
            </div>
        </div>
        @endif
    </div>
    
    <!-- Attendance Overview -->
    @if(isset($data['attendance_overview']))
    <div class="section">
        <div class="section-title">Attendance Overview</div>
        
        <div class="summary-stats">
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Attendance Records:</span>
                <span>{{ count($data['attendance_overview']['daily_stats']) }}</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Average Daily Present:</span>
                <span>{{ number_format(collect($data['attendance_overview']['daily_stats'])->avg('present'), 1) }}</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Average Daily Hours:</span>
                <span>{{ number_format(collect($data['attendance_overview']['daily_stats'])->avg('avg_hours'), 1) }}h</span>
            </div>
        </div>
        
        @if(isset($data['attendance_overview']['status_distribution']))
        <h4>Status Distribution</h4>
        <min-w-full divide-y divide-gray-200 class="data-min-w-full divide-y divide-gray-200">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $total = array_sum($data['attendance_overview']['status_distribution']);
                @endphp
                @foreach($data['attendance_overview']['status_distribution'] as $status => $count)
                <tr>
                    <td>{{ ucfirst($status) }}</td>
                    <td>{{ $count }}</td>
                    <td>{{ $total > 0 ? number_format(($count / $total) * 100, 1) : 0 }}%</td>
                </tr>
                @endforeach
            </tbody>
        </min-w-full divide-y divide-gray-200>
        @endif
    </div>
    @endif
    
    <!-- Leave Overview -->
    @if(isset($data['leave_overview']))
    <div class="section page-break">
        <div class="section-title">Leave Overview</div>
        
        @if(isset($data['leave_overview']['type_distribution']))
        <h4>Leave Type Distribution</h4>
        <min-w-full divide-y divide-gray-200 class="data-min-w-full divide-y divide-gray-200">
            <thead>
                <tr>
                    <th>Leave Type</th>
                    <th>Requests</th>
                    <th>Total Days</th>
                    <th>Approved</th>
                    <th>Approval Rate</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['leave_overview']['type_distribution'] as $type => $typeData)
                <tr>
                    <td>{{ $type }}</td>
                    <td>{{ $typeData['count'] }}</td>
                    <td>{{ $typeData['total_days'] }}</td>
                    <td>{{ $typeData['approved'] }}</td>
                    <td>{{ $typeData['count'] > 0 ? number_format(($typeData['approved'] / $typeData['count']) * 100, 1) : 0 }}%</td>
                </tr>
                @endforeach
            </tbody>
        </min-w-full divide-y divide-gray-200>
        @endif
        
        @if(isset($data['leave_overview']['approval_metrics']))
        <h4>Approval Metrics</h4>
        <div class="summary-stats">
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Requests:</span>
                <span>{{ $data['leave_overview']['approval_metrics']['total_requests'] }}</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Approval Rate:</span>
                <span>{{ number_format($data['leave_overview']['approval_metrics']['approval_rate'], 1) }}%</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Rejection Rate:</span>
                <span>{{ number_format($data['leave_overview']['approval_metrics']['rejection_rate'], 1) }}%</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Average Approval Time:</span>
                <span>{{ number_format($data['leave_overview']['approval_metrics']['avg_approval_time_hours'], 1) }} hours</span>
            </div>
        </div>
        @endif
    </div>
    @endif
    
    <!-- Payroll Overview -->
    @if(isset($data['payroll_overview']))
    <div class="section">
        <div class="section-title">Payroll Overview</div>
        
        @if(isset($data['payroll_overview']['cost_analysis']))
        <h4>Cost Analysis</h4>
        <div class="summary-stats">
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Cost:</span>
                <span>${{ number_format($data['payroll_overview']['cost_analysis']['total_cost'], 2) }}</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Hours:</span>
                <span>{{ number_format($data['payroll_overview']['cost_analysis']['total_hours'], 1) }}h</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Overtime:</span>
                <span>{{ number_format($data['payroll_overview']['cost_analysis']['total_overtime'], 1) }}h</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Cost per Hour:</span>
                <span>${{ number_format($data['payroll_overview']['cost_analysis']['cost_per_hour'], 2) }}</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Deductions:</span>
                <span>${{ number_format($data['payroll_overview']['cost_analysis']['total_deductions'], 2) }}</span>
            </div>
            <div class="stat-grid grid-cols-12 gap-4">
                <span class="stat-label">Total Bonuses:</span>
                <span>${{ number_format($data['payroll_overview']['cost_analysis']['total_bonuses'], 2) }}</span>
            </div>
        </div>
        @endif
        
        @if(isset($data['payroll_overview']['salary_distribution']))
        <h4>Salary Distribution</h4>
        <min-w-full divide-y divide-gray-200 class="data-min-w-full divide-y divide-gray-200">
            <thead>
                <tr>
                    <th>Salary Range</th>
                    <th>Employee Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['payroll_overview']['salary_distribution'] as $range => $count)
                <tr>
                    <td>${{ $range }}</td>
                    <td>{{ $count }}</td>
                </tr>
                @endforeach
            </tbody>
        </min-w-full divide-y divide-gray-200>
        @endif
    </div>
    @endif
    
    <!-- Employee Performance -->
    @if(isset($data['employee_performance']))
    <div class="section page-break">
        <div class="section-title">Employee Performance</div>
        
        @if(isset($data['employee_performance']['performance_distribution']))
        <h4>Performance Distribution</h4>
        <min-w-full divide-y divide-gray-200 class="data-min-w-full divide-y divide-gray-200">
            <thead>
                <tr>
                    <th>Performance Level</th>
                    <th>Employee Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['employee_performance']['performance_distribution'] as $level => $count)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $level)) }}</td>
                    <td>{{ $count }}</td>
                </tr>
                @endforeach
            </tbody>
        </min-w-full divide-y divide-gray-200>
        @endif
        
        @if(isset($data['employee_performance']['top_performers']))
        <h4>Top Performers</h4>
        <min-w-full divide-y divide-gray-200 class="data-min-w-full divide-y divide-gray-200">
            <thead>
                <tr>
                    <th>Employee</th>
                    <th>Attendance Rate</th>
                    <th>Punctuality Rate</th>
                    <th>Performance Score</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['employee_performance']['top_performers']->take(10) as $performer)
                <tr>
                    <td>{{ $performer['employee_name'] }}</td>
                    <td>{{ number_format($performer['attendance_rate'], 1) }}%</td>
                    <td>{{ number_format($performer['punctuality_rate'], 1) }}%</td>
                    <td>{{ number_format($performer['performance_score'], 1) }}</td>
                </tr>
                @endforeach
            </tbody>
        </min-w-full divide-y divide-gray-200>
        @endif
    </div>
    @endif
    
    <!-- Footer -->
    <div class="footer">
        <div>This report was automatically generated by the Attendance Management System</div>
        <div>For questions or support, please contact your system administrator</div>
    </div>
</body>
</html>